// Code generated by ent, DO NOT EDIT.

package cwmodel

import (
	"github.com/Kotodian/cwmodel/appmoduleinfo"
	"github.com/Kotodian/cwmodel/connector"
	"github.com/Kotodian/cwmodel/equipment"
	"github.com/Kotodian/cwmodel/equipmentalarm"
	"github.com/Kotodian/cwmodel/equipmentfirmwareeffect"
	"github.com/Kotodian/cwmodel/equipmentinfo"
	"github.com/Kotodian/cwmodel/equipmentiot"
	"github.com/Kotodian/cwmodel/equipmentlog"
	"github.com/Kotodian/cwmodel/evse"
	"github.com/Kotodian/cwmodel/firmware"
	"github.com/Kotodian/cwmodel/manufacturer"
	"github.com/Kotodian/cwmodel/model"
	"github.com/Kotodian/cwmodel/orderevent"
	"github.com/Kotodian/cwmodel/orderinfo"
	"github.com/Kotodian/cwmodel/reservation"
	"github.com/Kotodian/cwmodel/schema"
	"github.com/Kotodian/cwmodel/smartchargingeffect"
	"github.com/Kotodian/gokit/datasource"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appmoduleinfoFields := schema.AppModuleInfo{}.Fields()
	_ = appmoduleinfoFields
	// appmoduleinfoDescID is the schema descriptor for id field.
	appmoduleinfoDescID := appmoduleinfoFields[0].Descriptor()
	// appmoduleinfo.DefaultID holds the default value on creation for the id field.
	appmoduleinfo.DefaultID = datasource.UUID(appmoduleinfoDescID.Default.(uint64))
	connectorMixin := schema.Connector{}.Mixin()
	connectorMixinFields0 := connectorMixin[0].Fields()
	_ = connectorMixinFields0
	connectorFields := schema.Connector{}.Fields()
	_ = connectorFields
	// connectorDescVersion is the schema descriptor for version field.
	connectorDescVersion := connectorMixinFields0[1].Descriptor()
	// connector.DefaultVersion holds the default value on creation for the version field.
	connector.DefaultVersion = connectorDescVersion.Default.(int64)
	// connectorDescUpdatedAt is the schema descriptor for updated_at field.
	connectorDescUpdatedAt := connectorMixinFields0[5].Descriptor()
	// connector.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	connector.DefaultUpdatedAt = connectorDescUpdatedAt.Default.(int64)
	// connector.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	connector.UpdateDefaultUpdatedAt = connectorDescUpdatedAt.UpdateDefault.(func() int64)
	// connectorDescParkNo is the schema descriptor for park_no field.
	connectorDescParkNo := connectorFields[10].Descriptor()
	// connector.DefaultParkNo holds the default value on creation for the park_no field.
	connector.DefaultParkNo = connectorDescParkNo.Default.(string)
	equipmentMixin := schema.Equipment{}.Mixin()
	equipmentMixinFields0 := equipmentMixin[0].Fields()
	_ = equipmentMixinFields0
	equipmentFields := schema.Equipment{}.Fields()
	_ = equipmentFields
	// equipmentDescVersion is the schema descriptor for version field.
	equipmentDescVersion := equipmentMixinFields0[1].Descriptor()
	// equipment.DefaultVersion holds the default value on creation for the version field.
	equipment.DefaultVersion = equipmentDescVersion.Default.(int64)
	// equipmentDescUpdatedAt is the schema descriptor for updated_at field.
	equipmentDescUpdatedAt := equipmentMixinFields0[5].Descriptor()
	// equipment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	equipment.DefaultUpdatedAt = equipmentDescUpdatedAt.Default.(int64)
	// equipment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	equipment.UpdateDefaultUpdatedAt = equipmentDescUpdatedAt.UpdateDefault.(func() int64)
	// equipmentDescSn is the schema descriptor for sn field.
	equipmentDescSn := equipmentFields[0].Descriptor()
	// equipment.SnValidator is a validator for the "sn" field. It is called by the builders before save.
	equipment.SnValidator = equipmentDescSn.Validators[0].(func(string) error)
	equipmentalarmMixin := schema.EquipmentAlarm{}.Mixin()
	equipmentalarmMixinFields0 := equipmentalarmMixin[0].Fields()
	_ = equipmentalarmMixinFields0
	equipmentalarmFields := schema.EquipmentAlarm{}.Fields()
	_ = equipmentalarmFields
	// equipmentalarmDescVersion is the schema descriptor for version field.
	equipmentalarmDescVersion := equipmentalarmMixinFields0[1].Descriptor()
	// equipmentalarm.DefaultVersion holds the default value on creation for the version field.
	equipmentalarm.DefaultVersion = equipmentalarmDescVersion.Default.(int64)
	// equipmentalarmDescUpdatedAt is the schema descriptor for updated_at field.
	equipmentalarmDescUpdatedAt := equipmentalarmMixinFields0[5].Descriptor()
	// equipmentalarm.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	equipmentalarm.DefaultUpdatedAt = equipmentalarmDescUpdatedAt.Default.(int64)
	// equipmentalarm.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	equipmentalarm.UpdateDefaultUpdatedAt = equipmentalarmDescUpdatedAt.UpdateDefault.(func() int64)
	// equipmentalarmDescCount is the schema descriptor for count field.
	equipmentalarmDescCount := equipmentalarmFields[5].Descriptor()
	// equipmentalarm.DefaultCount holds the default value on creation for the count field.
	equipmentalarm.DefaultCount = equipmentalarmDescCount.Default.(int)
	equipmentfirmwareeffectMixin := schema.EquipmentFirmwareEffect{}.Mixin()
	equipmentfirmwareeffectMixinFields0 := equipmentfirmwareeffectMixin[0].Fields()
	_ = equipmentfirmwareeffectMixinFields0
	equipmentfirmwareeffectFields := schema.EquipmentFirmwareEffect{}.Fields()
	_ = equipmentfirmwareeffectFields
	// equipmentfirmwareeffectDescVersion is the schema descriptor for version field.
	equipmentfirmwareeffectDescVersion := equipmentfirmwareeffectMixinFields0[1].Descriptor()
	// equipmentfirmwareeffect.DefaultVersion holds the default value on creation for the version field.
	equipmentfirmwareeffect.DefaultVersion = equipmentfirmwareeffectDescVersion.Default.(int64)
	// equipmentfirmwareeffectDescUpdatedAt is the schema descriptor for updated_at field.
	equipmentfirmwareeffectDescUpdatedAt := equipmentfirmwareeffectMixinFields0[5].Descriptor()
	// equipmentfirmwareeffect.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	equipmentfirmwareeffect.DefaultUpdatedAt = equipmentfirmwareeffectDescUpdatedAt.Default.(int64)
	// equipmentfirmwareeffect.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	equipmentfirmwareeffect.UpdateDefaultUpdatedAt = equipmentfirmwareeffectDescUpdatedAt.UpdateDefault.(func() int64)
	equipmentinfoMixin := schema.EquipmentInfo{}.Mixin()
	equipmentinfoMixinFields0 := equipmentinfoMixin[0].Fields()
	_ = equipmentinfoMixinFields0
	equipmentinfoFields := schema.EquipmentInfo{}.Fields()
	_ = equipmentinfoFields
	// equipmentinfoDescVersion is the schema descriptor for version field.
	equipmentinfoDescVersion := equipmentinfoMixinFields0[1].Descriptor()
	// equipmentinfo.DefaultVersion holds the default value on creation for the version field.
	equipmentinfo.DefaultVersion = equipmentinfoDescVersion.Default.(int64)
	// equipmentinfoDescUpdatedAt is the schema descriptor for updated_at field.
	equipmentinfoDescUpdatedAt := equipmentinfoMixinFields0[5].Descriptor()
	// equipmentinfo.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	equipmentinfo.DefaultUpdatedAt = equipmentinfoDescUpdatedAt.Default.(int64)
	// equipmentinfo.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	equipmentinfo.UpdateDefaultUpdatedAt = equipmentinfoDescUpdatedAt.UpdateDefault.(func() int64)
	equipmentiotMixin := schema.EquipmentIot{}.Mixin()
	equipmentiotMixinFields0 := equipmentiotMixin[0].Fields()
	_ = equipmentiotMixinFields0
	equipmentiotFields := schema.EquipmentIot{}.Fields()
	_ = equipmentiotFields
	// equipmentiotDescVersion is the schema descriptor for version field.
	equipmentiotDescVersion := equipmentiotMixinFields0[1].Descriptor()
	// equipmentiot.DefaultVersion holds the default value on creation for the version field.
	equipmentiot.DefaultVersion = equipmentiotDescVersion.Default.(int64)
	// equipmentiotDescUpdatedAt is the schema descriptor for updated_at field.
	equipmentiotDescUpdatedAt := equipmentiotMixinFields0[5].Descriptor()
	// equipmentiot.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	equipmentiot.DefaultUpdatedAt = equipmentiotDescUpdatedAt.Default.(int64)
	// equipmentiot.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	equipmentiot.UpdateDefaultUpdatedAt = equipmentiotDescUpdatedAt.UpdateDefault.(func() int64)
	equipmentlogMixin := schema.EquipmentLog{}.Mixin()
	equipmentlogMixinFields0 := equipmentlogMixin[0].Fields()
	_ = equipmentlogMixinFields0
	equipmentlogFields := schema.EquipmentLog{}.Fields()
	_ = equipmentlogFields
	// equipmentlogDescVersion is the schema descriptor for version field.
	equipmentlogDescVersion := equipmentlogMixinFields0[1].Descriptor()
	// equipmentlog.DefaultVersion holds the default value on creation for the version field.
	equipmentlog.DefaultVersion = equipmentlogDescVersion.Default.(int64)
	// equipmentlogDescUpdatedAt is the schema descriptor for updated_at field.
	equipmentlogDescUpdatedAt := equipmentlogMixinFields0[5].Descriptor()
	// equipmentlog.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	equipmentlog.DefaultUpdatedAt = equipmentlogDescUpdatedAt.Default.(int64)
	// equipmentlog.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	equipmentlog.UpdateDefaultUpdatedAt = equipmentlogDescUpdatedAt.UpdateDefault.(func() int64)
	evseMixin := schema.Evse{}.Mixin()
	evseMixinFields0 := evseMixin[0].Fields()
	_ = evseMixinFields0
	evseFields := schema.Evse{}.Fields()
	_ = evseFields
	// evseDescVersion is the schema descriptor for version field.
	evseDescVersion := evseMixinFields0[1].Descriptor()
	// evse.DefaultVersion holds the default value on creation for the version field.
	evse.DefaultVersion = evseDescVersion.Default.(int64)
	// evseDescUpdatedAt is the schema descriptor for updated_at field.
	evseDescUpdatedAt := evseMixinFields0[5].Descriptor()
	// evse.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	evse.DefaultUpdatedAt = evseDescUpdatedAt.Default.(int64)
	// evse.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	evse.UpdateDefaultUpdatedAt = evseDescUpdatedAt.UpdateDefault.(func() int64)
	firmwareMixin := schema.Firmware{}.Mixin()
	firmwareMixinFields0 := firmwareMixin[0].Fields()
	_ = firmwareMixinFields0
	firmwareFields := schema.Firmware{}.Fields()
	_ = firmwareFields
	// firmwareDescVersion is the schema descriptor for version field.
	firmwareDescVersion := firmwareMixinFields0[1].Descriptor()
	// firmware.DefaultVersion holds the default value on creation for the version field.
	firmware.DefaultVersion = firmwareDescVersion.Default.(int64)
	// firmwareDescUpdatedAt is the schema descriptor for updated_at field.
	firmwareDescUpdatedAt := firmwareMixinFields0[5].Descriptor()
	// firmware.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	firmware.DefaultUpdatedAt = firmwareDescUpdatedAt.Default.(int64)
	// firmware.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	firmware.UpdateDefaultUpdatedAt = firmwareDescUpdatedAt.UpdateDefault.(func() int64)
	manufacturerMixin := schema.Manufacturer{}.Mixin()
	manufacturerMixinFields0 := manufacturerMixin[0].Fields()
	_ = manufacturerMixinFields0
	manufacturerFields := schema.Manufacturer{}.Fields()
	_ = manufacturerFields
	// manufacturerDescVersion is the schema descriptor for version field.
	manufacturerDescVersion := manufacturerMixinFields0[1].Descriptor()
	// manufacturer.DefaultVersion holds the default value on creation for the version field.
	manufacturer.DefaultVersion = manufacturerDescVersion.Default.(int64)
	// manufacturerDescUpdatedAt is the schema descriptor for updated_at field.
	manufacturerDescUpdatedAt := manufacturerMixinFields0[5].Descriptor()
	// manufacturer.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	manufacturer.DefaultUpdatedAt = manufacturerDescUpdatedAt.Default.(int64)
	// manufacturer.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	manufacturer.UpdateDefaultUpdatedAt = manufacturerDescUpdatedAt.UpdateDefault.(func() int64)
	modelMixin := schema.Model{}.Mixin()
	modelMixinFields0 := modelMixin[0].Fields()
	_ = modelMixinFields0
	modelFields := schema.Model{}.Fields()
	_ = modelFields
	// modelDescVersion is the schema descriptor for version field.
	modelDescVersion := modelMixinFields0[1].Descriptor()
	// model.DefaultVersion holds the default value on creation for the version field.
	model.DefaultVersion = modelDescVersion.Default.(int64)
	// modelDescUpdatedAt is the schema descriptor for updated_at field.
	modelDescUpdatedAt := modelMixinFields0[5].Descriptor()
	// model.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	model.DefaultUpdatedAt = modelDescUpdatedAt.Default.(int64)
	// model.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	model.UpdateDefaultUpdatedAt = modelDescUpdatedAt.UpdateDefault.(func() int64)
	ordereventFields := schema.OrderEvent{}.Fields()
	_ = ordereventFields
	// ordereventDescID is the schema descriptor for id field.
	ordereventDescID := ordereventFields[0].Descriptor()
	// orderevent.DefaultID holds the default value on creation for the id field.
	orderevent.DefaultID = datasource.UUID(ordereventDescID.Default.(uint64))
	orderinfoMixin := schema.OrderInfo{}.Mixin()
	orderinfoMixinFields0 := orderinfoMixin[0].Fields()
	_ = orderinfoMixinFields0
	orderinfoFields := schema.OrderInfo{}.Fields()
	_ = orderinfoFields
	// orderinfoDescVersion is the schema descriptor for version field.
	orderinfoDescVersion := orderinfoMixinFields0[1].Descriptor()
	// orderinfo.DefaultVersion holds the default value on creation for the version field.
	orderinfo.DefaultVersion = orderinfoDescVersion.Default.(int64)
	// orderinfoDescUpdatedAt is the schema descriptor for updated_at field.
	orderinfoDescUpdatedAt := orderinfoMixinFields0[5].Descriptor()
	// orderinfo.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	orderinfo.DefaultUpdatedAt = orderinfoDescUpdatedAt.Default.(int64)
	// orderinfo.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	orderinfo.UpdateDefaultUpdatedAt = orderinfoDescUpdatedAt.UpdateDefault.(func() int64)
	reservationMixin := schema.Reservation{}.Mixin()
	reservationMixinFields0 := reservationMixin[0].Fields()
	_ = reservationMixinFields0
	reservationFields := schema.Reservation{}.Fields()
	_ = reservationFields
	// reservationDescVersion is the schema descriptor for version field.
	reservationDescVersion := reservationMixinFields0[1].Descriptor()
	// reservation.DefaultVersion holds the default value on creation for the version field.
	reservation.DefaultVersion = reservationDescVersion.Default.(int64)
	// reservationDescUpdatedAt is the schema descriptor for updated_at field.
	reservationDescUpdatedAt := reservationMixinFields0[5].Descriptor()
	// reservation.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	reservation.DefaultUpdatedAt = reservationDescUpdatedAt.Default.(int64)
	// reservation.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	reservation.UpdateDefaultUpdatedAt = reservationDescUpdatedAt.UpdateDefault.(func() int64)
	smartchargingeffectMixin := schema.SmartChargingEffect{}.Mixin()
	smartchargingeffectMixinFields0 := smartchargingeffectMixin[0].Fields()
	_ = smartchargingeffectMixinFields0
	smartchargingeffectFields := schema.SmartChargingEffect{}.Fields()
	_ = smartchargingeffectFields
	// smartchargingeffectDescVersion is the schema descriptor for version field.
	smartchargingeffectDescVersion := smartchargingeffectMixinFields0[1].Descriptor()
	// smartchargingeffect.DefaultVersion holds the default value on creation for the version field.
	smartchargingeffect.DefaultVersion = smartchargingeffectDescVersion.Default.(int64)
	// smartchargingeffectDescUpdatedAt is the schema descriptor for updated_at field.
	smartchargingeffectDescUpdatedAt := smartchargingeffectMixinFields0[5].Descriptor()
	// smartchargingeffect.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	smartchargingeffect.DefaultUpdatedAt = smartchargingeffectDescUpdatedAt.Default.(int64)
	// smartchargingeffect.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	smartchargingeffect.UpdateDefaultUpdatedAt = smartchargingeffectDescUpdatedAt.UpdateDefault.(func() int64)
}
