// Code generated by ent, DO NOT EDIT.

package manufacturer

const (
	// Label holds the string label denoting the manufacturer type in the database.
	Label = "manufacturer"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// Table holds the table name of the manufacturer in the database.
	Table = "equip_manufacturer"
)

// Columns holds all SQL columns for manufacturer fields.
var Columns = []string{
	FieldID,
	FieldCode,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
