// Code generated by entc, DO NOT EDIT.

package equipmentfirmwareeffect

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Kotodian/ent-practice/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.EquipmentFirmwareEffect {
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.EquipmentFirmwareEffect {
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.EquipmentFirmwareEffect {
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.EquipmentFirmwareEffect {
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.EquipmentFirmwareEffect {
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.EquipmentFirmwareEffect {
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.EquipmentFirmwareEffect {
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.EquipmentFirmwareEffect {
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.EquipmentFirmwareEffect {
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v int64) predicate.EquipmentFirmwareEffect {
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRequestID), v))
	})
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v int) predicate.EquipmentFirmwareEffect {
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldState), v))
	})
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v int64) predicate.EquipmentFirmwareEffect {
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldRequestID), v))
	})
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v int64) predicate.EquipmentFirmwareEffect {
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldRequestID), v))
	})
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...int64) predicate.EquipmentFirmwareEffect {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldRequestID), v...))
	})
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...int64) predicate.EquipmentFirmwareEffect {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldRequestID), v...))
	})
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v int64) predicate.EquipmentFirmwareEffect {
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldRequestID), v))
	})
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v int64) predicate.EquipmentFirmwareEffect {
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldRequestID), v))
	})
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v int64) predicate.EquipmentFirmwareEffect {
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldRequestID), v))
	})
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v int64) predicate.EquipmentFirmwareEffect {
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldRequestID), v))
	})
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v int) predicate.EquipmentFirmwareEffect {
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldState), v))
	})
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v int) predicate.EquipmentFirmwareEffect {
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldState), v))
	})
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...int) predicate.EquipmentFirmwareEffect {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldState), v...))
	})
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...int) predicate.EquipmentFirmwareEffect {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldState), v...))
	})
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v int) predicate.EquipmentFirmwareEffect {
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldState), v))
	})
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v int) predicate.EquipmentFirmwareEffect {
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldState), v))
	})
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v int) predicate.EquipmentFirmwareEffect {
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldState), v))
	})
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v int) predicate.EquipmentFirmwareEffect {
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldState), v))
	})
}

// HasEquipment applies the HasEdge predicate on the "equipment" edge.
func HasEquipment() predicate.EquipmentFirmwareEffect {
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(EquipmentTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EquipmentTable, EquipmentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEquipmentWith applies the HasEdge predicate on the "equipment" edge with a given conditions (other predicates).
func HasEquipmentWith(preds ...predicate.Equipment) predicate.EquipmentFirmwareEffect {
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(EquipmentInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EquipmentTable, EquipmentColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasFirmware applies the HasEdge predicate on the "firmware" edge.
func HasFirmware() predicate.EquipmentFirmwareEffect {
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(FirmwareTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FirmwareTable, FirmwareColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFirmwareWith applies the HasEdge predicate on the "firmware" edge with a given conditions (other predicates).
func HasFirmwareWith(preds ...predicate.Firmware) predicate.EquipmentFirmwareEffect {
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(FirmwareInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FirmwareTable, FirmwareColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EquipmentFirmwareEffect) predicate.EquipmentFirmwareEffect {
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EquipmentFirmwareEffect) predicate.EquipmentFirmwareEffect {
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EquipmentFirmwareEffect) predicate.EquipmentFirmwareEffect {
	return predicate.EquipmentFirmwareEffect(func(s *sql.Selector) {
		p(s.Not())
	})
}
