// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AppModuleInfo is the predicate function for appmoduleinfo builders.
type AppModuleInfo func(*sql.Selector)

// Connector is the predicate function for connector builders.
type Connector func(*sql.Selector)

// Equipment is the predicate function for equipment builders.
type Equipment func(*sql.Selector)

// EquipmentAlarm is the predicate function for equipmentalarm builders.
type EquipmentAlarm func(*sql.Selector)

// EquipmentFirmwareEffect is the predicate function for equipmentfirmwareeffect builders.
type EquipmentFirmwareEffect func(*sql.Selector)

// EquipmentInfo is the predicate function for equipmentinfo builders.
type EquipmentInfo func(*sql.Selector)

// EquipmentIot is the predicate function for equipmentiot builders.
type EquipmentIot func(*sql.Selector)

// EquipmentLog is the predicate function for equipmentlog builders.
type EquipmentLog func(*sql.Selector)

// Evse is the predicate function for evse builders.
type Evse func(*sql.Selector)

// Firmware is the predicate function for firmware builders.
type Firmware func(*sql.Selector)

// Manufacturer is the predicate function for manufacturer builders.
type Manufacturer func(*sql.Selector)

// Model is the predicate function for model builders.
type Model func(*sql.Selector)

// OrderEvent is the predicate function for orderevent builders.
type OrderEvent func(*sql.Selector)

// OrderInfo is the predicate function for orderinfo builders.
type OrderInfo func(*sql.Selector)

// Reservation is the predicate function for reservation builders.
type Reservation func(*sql.Selector)

// SmartChargingEffect is the predicate function for smartchargingeffect builders.
type SmartChargingEffect func(*sql.Selector)
