// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Kotodian/ent-practice/ent/connector"
	"github.com/Kotodian/ent-practice/ent/equipment"
	"github.com/Kotodian/ent-practice/ent/evse"
	"github.com/Kotodian/ent-practice/ent/orderinfo"
	"github.com/Kotodian/ent-practice/ent/predicate"
	"github.com/Kotodian/ent-practice/ent/reservation"
	"github.com/Kotodian/ent-practice/ent/smartchargingeffect"
	"github.com/Kotodian/gokit/datasource"
)

// ConnectorUpdate is the builder for updating Connector entities.
type ConnectorUpdate struct {
	config
	hooks    []Hook
	mutation *ConnectorMutation
}

// Where appends a list predicates to the ConnectorUpdate builder.
func (cu *ConnectorUpdate) Where(ps ...predicate.Connector) *ConnectorUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetVersion sets the "version" field.
func (cu *ConnectorUpdate) SetVersion(i int64) *ConnectorUpdate {
	cu.mutation.ResetVersion()
	cu.mutation.SetVersion(i)
	return cu
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (cu *ConnectorUpdate) SetNillableVersion(i *int64) *ConnectorUpdate {
	if i != nil {
		cu.SetVersion(*i)
	}
	return cu
}

// AddVersion adds i to the "version" field.
func (cu *ConnectorUpdate) AddVersion(i int64) *ConnectorUpdate {
	cu.mutation.AddVersion(i)
	return cu
}

// SetUpdatedBy sets the "updated_by" field.
func (cu *ConnectorUpdate) SetUpdatedBy(d datasource.UUID) *ConnectorUpdate {
	cu.mutation.ResetUpdatedBy()
	cu.mutation.SetUpdatedBy(d)
	return cu
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (cu *ConnectorUpdate) SetNillableUpdatedBy(d *datasource.UUID) *ConnectorUpdate {
	if d != nil {
		cu.SetUpdatedBy(*d)
	}
	return cu
}

// AddUpdatedBy adds d to the "updated_by" field.
func (cu *ConnectorUpdate) AddUpdatedBy(d datasource.UUID) *ConnectorUpdate {
	cu.mutation.AddUpdatedBy(d)
	return cu
}

// SetUpdatedAt sets the "updated_at" field.
func (cu *ConnectorUpdate) SetUpdatedAt(i int64) *ConnectorUpdate {
	cu.mutation.ResetUpdatedAt()
	cu.mutation.SetUpdatedAt(i)
	return cu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cu *ConnectorUpdate) SetNillableUpdatedAt(i *int64) *ConnectorUpdate {
	if i != nil {
		cu.SetUpdatedAt(*i)
	}
	return cu
}

// AddUpdatedAt adds i to the "updated_at" field.
func (cu *ConnectorUpdate) AddUpdatedAt(i int64) *ConnectorUpdate {
	cu.mutation.AddUpdatedAt(i)
	return cu
}

// SetEquipmentSn sets the "equipment_sn" field.
func (cu *ConnectorUpdate) SetEquipmentSn(s string) *ConnectorUpdate {
	cu.mutation.SetEquipmentSn(s)
	return cu
}

// SetEvseSerial sets the "evse_serial" field.
func (cu *ConnectorUpdate) SetEvseSerial(s string) *ConnectorUpdate {
	cu.mutation.SetEvseSerial(s)
	return cu
}

// SetSerial sets the "serial" field.
func (cu *ConnectorUpdate) SetSerial(s string) *ConnectorUpdate {
	cu.mutation.SetSerial(s)
	return cu
}

// SetCurrentState sets the "current_state" field.
func (cu *ConnectorUpdate) SetCurrentState(i int) *ConnectorUpdate {
	cu.mutation.ResetCurrentState()
	cu.mutation.SetCurrentState(i)
	return cu
}

// AddCurrentState adds i to the "current_state" field.
func (cu *ConnectorUpdate) AddCurrentState(i int) *ConnectorUpdate {
	cu.mutation.AddCurrentState(i)
	return cu
}

// SetBeforeState sets the "before_state" field.
func (cu *ConnectorUpdate) SetBeforeState(i int) *ConnectorUpdate {
	cu.mutation.ResetBeforeState()
	cu.mutation.SetBeforeState(i)
	return cu
}

// AddBeforeState adds i to the "before_state" field.
func (cu *ConnectorUpdate) AddBeforeState(i int) *ConnectorUpdate {
	cu.mutation.AddBeforeState(i)
	return cu
}

// SetChargingState sets the "charging_state" field.
func (cu *ConnectorUpdate) SetChargingState(i int) *ConnectorUpdate {
	cu.mutation.ResetChargingState()
	cu.mutation.SetChargingState(i)
	return cu
}

// SetNillableChargingState sets the "charging_state" field if the given value is not nil.
func (cu *ConnectorUpdate) SetNillableChargingState(i *int) *ConnectorUpdate {
	if i != nil {
		cu.SetChargingState(*i)
	}
	return cu
}

// AddChargingState adds i to the "charging_state" field.
func (cu *ConnectorUpdate) AddChargingState(i int) *ConnectorUpdate {
	cu.mutation.AddChargingState(i)
	return cu
}

// ClearChargingState clears the value of the "charging_state" field.
func (cu *ConnectorUpdate) ClearChargingState() *ConnectorUpdate {
	cu.mutation.ClearChargingState()
	return cu
}

// SetReservationID sets the "reservation_id" field.
func (cu *ConnectorUpdate) SetReservationID(d datasource.UUID) *ConnectorUpdate {
	cu.mutation.ResetReservationID()
	cu.mutation.SetReservationID(d)
	return cu
}

// SetNillableReservationID sets the "reservation_id" field if the given value is not nil.
func (cu *ConnectorUpdate) SetNillableReservationID(d *datasource.UUID) *ConnectorUpdate {
	if d != nil {
		cu.SetReservationID(*d)
	}
	return cu
}

// AddReservationID adds d to the "reservation_id" field.
func (cu *ConnectorUpdate) AddReservationID(d datasource.UUID) *ConnectorUpdate {
	cu.mutation.AddReservationID(d)
	return cu
}

// ClearReservationID clears the value of the "reservation_id" field.
func (cu *ConnectorUpdate) ClearReservationID() *ConnectorUpdate {
	cu.mutation.ClearReservationID()
	return cu
}

// SetParkNo sets the "park_no" field.
func (cu *ConnectorUpdate) SetParkNo(s string) *ConnectorUpdate {
	cu.mutation.SetParkNo(s)
	return cu
}

// SetNillableParkNo sets the "park_no" field if the given value is not nil.
func (cu *ConnectorUpdate) SetNillableParkNo(s *string) *ConnectorUpdate {
	if s != nil {
		cu.SetParkNo(*s)
	}
	return cu
}

// SetEvseID sets the "evse" edge to the Evse entity by ID.
func (cu *ConnectorUpdate) SetEvseID(id datasource.UUID) *ConnectorUpdate {
	cu.mutation.SetEvseID(id)
	return cu
}

// SetEvse sets the "evse" edge to the Evse entity.
func (cu *ConnectorUpdate) SetEvse(e *Evse) *ConnectorUpdate {
	return cu.SetEvseID(e.ID)
}

// SetEquipmentID sets the "equipment" edge to the Equipment entity by ID.
func (cu *ConnectorUpdate) SetEquipmentID(id datasource.UUID) *ConnectorUpdate {
	cu.mutation.SetEquipmentID(id)
	return cu
}

// SetEquipment sets the "equipment" edge to the Equipment entity.
func (cu *ConnectorUpdate) SetEquipment(e *Equipment) *ConnectorUpdate {
	return cu.SetEquipmentID(e.ID)
}

// AddOrderInfoIDs adds the "order_info" edge to the OrderInfo entity by IDs.
func (cu *ConnectorUpdate) AddOrderInfoIDs(ids ...datasource.UUID) *ConnectorUpdate {
	cu.mutation.AddOrderInfoIDs(ids...)
	return cu
}

// AddOrderInfo adds the "order_info" edges to the OrderInfo entity.
func (cu *ConnectorUpdate) AddOrderInfo(o ...*OrderInfo) *ConnectorUpdate {
	ids := make([]datasource.UUID, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return cu.AddOrderInfoIDs(ids...)
}

// AddReservationIDs adds the "reservation" edge to the Reservation entity by IDs.
func (cu *ConnectorUpdate) AddReservationIDs(ids ...datasource.UUID) *ConnectorUpdate {
	cu.mutation.AddReservationIDs(ids...)
	return cu
}

// AddReservation adds the "reservation" edges to the Reservation entity.
func (cu *ConnectorUpdate) AddReservation(r ...*Reservation) *ConnectorUpdate {
	ids := make([]datasource.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return cu.AddReservationIDs(ids...)
}

// AddSmartChargingEffectIDs adds the "smart_charging_effect" edge to the SmartChargingEffect entity by IDs.
func (cu *ConnectorUpdate) AddSmartChargingEffectIDs(ids ...datasource.UUID) *ConnectorUpdate {
	cu.mutation.AddSmartChargingEffectIDs(ids...)
	return cu
}

// AddSmartChargingEffect adds the "smart_charging_effect" edges to the SmartChargingEffect entity.
func (cu *ConnectorUpdate) AddSmartChargingEffect(s ...*SmartChargingEffect) *ConnectorUpdate {
	ids := make([]datasource.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return cu.AddSmartChargingEffectIDs(ids...)
}

// Mutation returns the ConnectorMutation object of the builder.
func (cu *ConnectorUpdate) Mutation() *ConnectorMutation {
	return cu.mutation
}

// ClearEvse clears the "evse" edge to the Evse entity.
func (cu *ConnectorUpdate) ClearEvse() *ConnectorUpdate {
	cu.mutation.ClearEvse()
	return cu
}

// ClearEquipment clears the "equipment" edge to the Equipment entity.
func (cu *ConnectorUpdate) ClearEquipment() *ConnectorUpdate {
	cu.mutation.ClearEquipment()
	return cu
}

// ClearOrderInfo clears all "order_info" edges to the OrderInfo entity.
func (cu *ConnectorUpdate) ClearOrderInfo() *ConnectorUpdate {
	cu.mutation.ClearOrderInfo()
	return cu
}

// RemoveOrderInfoIDs removes the "order_info" edge to OrderInfo entities by IDs.
func (cu *ConnectorUpdate) RemoveOrderInfoIDs(ids ...datasource.UUID) *ConnectorUpdate {
	cu.mutation.RemoveOrderInfoIDs(ids...)
	return cu
}

// RemoveOrderInfo removes "order_info" edges to OrderInfo entities.
func (cu *ConnectorUpdate) RemoveOrderInfo(o ...*OrderInfo) *ConnectorUpdate {
	ids := make([]datasource.UUID, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return cu.RemoveOrderInfoIDs(ids...)
}

// ClearReservation clears all "reservation" edges to the Reservation entity.
func (cu *ConnectorUpdate) ClearReservation() *ConnectorUpdate {
	cu.mutation.ClearReservation()
	return cu
}

// RemoveReservationIDs removes the "reservation" edge to Reservation entities by IDs.
func (cu *ConnectorUpdate) RemoveReservationIDs(ids ...datasource.UUID) *ConnectorUpdate {
	cu.mutation.RemoveReservationIDs(ids...)
	return cu
}

// RemoveReservation removes "reservation" edges to Reservation entities.
func (cu *ConnectorUpdate) RemoveReservation(r ...*Reservation) *ConnectorUpdate {
	ids := make([]datasource.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return cu.RemoveReservationIDs(ids...)
}

// ClearSmartChargingEffect clears all "smart_charging_effect" edges to the SmartChargingEffect entity.
func (cu *ConnectorUpdate) ClearSmartChargingEffect() *ConnectorUpdate {
	cu.mutation.ClearSmartChargingEffect()
	return cu
}

// RemoveSmartChargingEffectIDs removes the "smart_charging_effect" edge to SmartChargingEffect entities by IDs.
func (cu *ConnectorUpdate) RemoveSmartChargingEffectIDs(ids ...datasource.UUID) *ConnectorUpdate {
	cu.mutation.RemoveSmartChargingEffectIDs(ids...)
	return cu
}

// RemoveSmartChargingEffect removes "smart_charging_effect" edges to SmartChargingEffect entities.
func (cu *ConnectorUpdate) RemoveSmartChargingEffect(s ...*SmartChargingEffect) *ConnectorUpdate {
	ids := make([]datasource.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return cu.RemoveSmartChargingEffectIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *ConnectorUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cu.hooks) == 0 {
		if err = cu.check(); err != nil {
			return 0, err
		}
		affected, err = cu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ConnectorMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cu.check(); err != nil {
				return 0, err
			}
			cu.mutation = mutation
			affected, err = cu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cu.hooks) - 1; i >= 0; i-- {
			if cu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (cu *ConnectorUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *ConnectorUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *ConnectorUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *ConnectorUpdate) check() error {
	if _, ok := cu.mutation.EvseID(); cu.mutation.EvseCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Connector.evse"`)
	}
	if _, ok := cu.mutation.EquipmentID(); cu.mutation.EquipmentCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Connector.equipment"`)
	}
	return nil
}

func (cu *ConnectorUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   connector.Table,
			Columns: connector.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: connector.FieldID,
			},
		},
	}
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Version(); ok {
		_spec.SetField(connector.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := cu.mutation.AddedVersion(); ok {
		_spec.AddField(connector.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := cu.mutation.UpdatedBy(); ok {
		_spec.SetField(connector.FieldUpdatedBy, field.TypeUint64, value)
	}
	if value, ok := cu.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(connector.FieldUpdatedBy, field.TypeUint64, value)
	}
	if value, ok := cu.mutation.UpdatedAt(); ok {
		_spec.SetField(connector.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := cu.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(connector.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := cu.mutation.EquipmentSn(); ok {
		_spec.SetField(connector.FieldEquipmentSn, field.TypeString, value)
	}
	if value, ok := cu.mutation.EvseSerial(); ok {
		_spec.SetField(connector.FieldEvseSerial, field.TypeString, value)
	}
	if value, ok := cu.mutation.Serial(); ok {
		_spec.SetField(connector.FieldSerial, field.TypeString, value)
	}
	if value, ok := cu.mutation.CurrentState(); ok {
		_spec.SetField(connector.FieldCurrentState, field.TypeInt, value)
	}
	if value, ok := cu.mutation.AddedCurrentState(); ok {
		_spec.AddField(connector.FieldCurrentState, field.TypeInt, value)
	}
	if value, ok := cu.mutation.BeforeState(); ok {
		_spec.SetField(connector.FieldBeforeState, field.TypeInt, value)
	}
	if value, ok := cu.mutation.AddedBeforeState(); ok {
		_spec.AddField(connector.FieldBeforeState, field.TypeInt, value)
	}
	if value, ok := cu.mutation.ChargingState(); ok {
		_spec.SetField(connector.FieldChargingState, field.TypeInt, value)
	}
	if value, ok := cu.mutation.AddedChargingState(); ok {
		_spec.AddField(connector.FieldChargingState, field.TypeInt, value)
	}
	if cu.mutation.ChargingStateCleared() {
		_spec.ClearField(connector.FieldChargingState, field.TypeInt)
	}
	if value, ok := cu.mutation.ReservationID(); ok {
		_spec.SetField(connector.FieldReservationID, field.TypeUint64, value)
	}
	if value, ok := cu.mutation.AddedReservationID(); ok {
		_spec.AddField(connector.FieldReservationID, field.TypeUint64, value)
	}
	if cu.mutation.ReservationIDCleared() {
		_spec.ClearField(connector.FieldReservationID, field.TypeUint64)
	}
	if value, ok := cu.mutation.ParkNo(); ok {
		_spec.SetField(connector.FieldParkNo, field.TypeString, value)
	}
	if cu.mutation.EvseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   connector.EvseTable,
			Columns: []string{connector.EvseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: evse.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.EvseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   connector.EvseTable,
			Columns: []string{connector.EvseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: evse.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.EquipmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   connector.EquipmentTable,
			Columns: []string{connector.EquipmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: equipment.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.EquipmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   connector.EquipmentTable,
			Columns: []string{connector.EquipmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: equipment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.OrderInfoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   connector.OrderInfoTable,
			Columns: []string{connector.OrderInfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: orderinfo.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedOrderInfoIDs(); len(nodes) > 0 && !cu.mutation.OrderInfoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   connector.OrderInfoTable,
			Columns: []string{connector.OrderInfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: orderinfo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.OrderInfoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   connector.OrderInfoTable,
			Columns: []string{connector.OrderInfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: orderinfo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.ReservationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   connector.ReservationTable,
			Columns: []string{connector.ReservationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: reservation.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedReservationIDs(); len(nodes) > 0 && !cu.mutation.ReservationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   connector.ReservationTable,
			Columns: []string{connector.ReservationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: reservation.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.ReservationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   connector.ReservationTable,
			Columns: []string{connector.ReservationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: reservation.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.SmartChargingEffectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   connector.SmartChargingEffectTable,
			Columns: []string{connector.SmartChargingEffectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: smartchargingeffect.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedSmartChargingEffectIDs(); len(nodes) > 0 && !cu.mutation.SmartChargingEffectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   connector.SmartChargingEffectTable,
			Columns: []string{connector.SmartChargingEffectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: smartchargingeffect.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.SmartChargingEffectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   connector.SmartChargingEffectTable,
			Columns: []string{connector.SmartChargingEffectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: smartchargingeffect.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{connector.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// ConnectorUpdateOne is the builder for updating a single Connector entity.
type ConnectorUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ConnectorMutation
}

// SetVersion sets the "version" field.
func (cuo *ConnectorUpdateOne) SetVersion(i int64) *ConnectorUpdateOne {
	cuo.mutation.ResetVersion()
	cuo.mutation.SetVersion(i)
	return cuo
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (cuo *ConnectorUpdateOne) SetNillableVersion(i *int64) *ConnectorUpdateOne {
	if i != nil {
		cuo.SetVersion(*i)
	}
	return cuo
}

// AddVersion adds i to the "version" field.
func (cuo *ConnectorUpdateOne) AddVersion(i int64) *ConnectorUpdateOne {
	cuo.mutation.AddVersion(i)
	return cuo
}

// SetUpdatedBy sets the "updated_by" field.
func (cuo *ConnectorUpdateOne) SetUpdatedBy(d datasource.UUID) *ConnectorUpdateOne {
	cuo.mutation.ResetUpdatedBy()
	cuo.mutation.SetUpdatedBy(d)
	return cuo
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (cuo *ConnectorUpdateOne) SetNillableUpdatedBy(d *datasource.UUID) *ConnectorUpdateOne {
	if d != nil {
		cuo.SetUpdatedBy(*d)
	}
	return cuo
}

// AddUpdatedBy adds d to the "updated_by" field.
func (cuo *ConnectorUpdateOne) AddUpdatedBy(d datasource.UUID) *ConnectorUpdateOne {
	cuo.mutation.AddUpdatedBy(d)
	return cuo
}

// SetUpdatedAt sets the "updated_at" field.
func (cuo *ConnectorUpdateOne) SetUpdatedAt(i int64) *ConnectorUpdateOne {
	cuo.mutation.ResetUpdatedAt()
	cuo.mutation.SetUpdatedAt(i)
	return cuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cuo *ConnectorUpdateOne) SetNillableUpdatedAt(i *int64) *ConnectorUpdateOne {
	if i != nil {
		cuo.SetUpdatedAt(*i)
	}
	return cuo
}

// AddUpdatedAt adds i to the "updated_at" field.
func (cuo *ConnectorUpdateOne) AddUpdatedAt(i int64) *ConnectorUpdateOne {
	cuo.mutation.AddUpdatedAt(i)
	return cuo
}

// SetEquipmentSn sets the "equipment_sn" field.
func (cuo *ConnectorUpdateOne) SetEquipmentSn(s string) *ConnectorUpdateOne {
	cuo.mutation.SetEquipmentSn(s)
	return cuo
}

// SetEvseSerial sets the "evse_serial" field.
func (cuo *ConnectorUpdateOne) SetEvseSerial(s string) *ConnectorUpdateOne {
	cuo.mutation.SetEvseSerial(s)
	return cuo
}

// SetSerial sets the "serial" field.
func (cuo *ConnectorUpdateOne) SetSerial(s string) *ConnectorUpdateOne {
	cuo.mutation.SetSerial(s)
	return cuo
}

// SetCurrentState sets the "current_state" field.
func (cuo *ConnectorUpdateOne) SetCurrentState(i int) *ConnectorUpdateOne {
	cuo.mutation.ResetCurrentState()
	cuo.mutation.SetCurrentState(i)
	return cuo
}

// AddCurrentState adds i to the "current_state" field.
func (cuo *ConnectorUpdateOne) AddCurrentState(i int) *ConnectorUpdateOne {
	cuo.mutation.AddCurrentState(i)
	return cuo
}

// SetBeforeState sets the "before_state" field.
func (cuo *ConnectorUpdateOne) SetBeforeState(i int) *ConnectorUpdateOne {
	cuo.mutation.ResetBeforeState()
	cuo.mutation.SetBeforeState(i)
	return cuo
}

// AddBeforeState adds i to the "before_state" field.
func (cuo *ConnectorUpdateOne) AddBeforeState(i int) *ConnectorUpdateOne {
	cuo.mutation.AddBeforeState(i)
	return cuo
}

// SetChargingState sets the "charging_state" field.
func (cuo *ConnectorUpdateOne) SetChargingState(i int) *ConnectorUpdateOne {
	cuo.mutation.ResetChargingState()
	cuo.mutation.SetChargingState(i)
	return cuo
}

// SetNillableChargingState sets the "charging_state" field if the given value is not nil.
func (cuo *ConnectorUpdateOne) SetNillableChargingState(i *int) *ConnectorUpdateOne {
	if i != nil {
		cuo.SetChargingState(*i)
	}
	return cuo
}

// AddChargingState adds i to the "charging_state" field.
func (cuo *ConnectorUpdateOne) AddChargingState(i int) *ConnectorUpdateOne {
	cuo.mutation.AddChargingState(i)
	return cuo
}

// ClearChargingState clears the value of the "charging_state" field.
func (cuo *ConnectorUpdateOne) ClearChargingState() *ConnectorUpdateOne {
	cuo.mutation.ClearChargingState()
	return cuo
}

// SetReservationID sets the "reservation_id" field.
func (cuo *ConnectorUpdateOne) SetReservationID(d datasource.UUID) *ConnectorUpdateOne {
	cuo.mutation.ResetReservationID()
	cuo.mutation.SetReservationID(d)
	return cuo
}

// SetNillableReservationID sets the "reservation_id" field if the given value is not nil.
func (cuo *ConnectorUpdateOne) SetNillableReservationID(d *datasource.UUID) *ConnectorUpdateOne {
	if d != nil {
		cuo.SetReservationID(*d)
	}
	return cuo
}

// AddReservationID adds d to the "reservation_id" field.
func (cuo *ConnectorUpdateOne) AddReservationID(d datasource.UUID) *ConnectorUpdateOne {
	cuo.mutation.AddReservationID(d)
	return cuo
}

// ClearReservationID clears the value of the "reservation_id" field.
func (cuo *ConnectorUpdateOne) ClearReservationID() *ConnectorUpdateOne {
	cuo.mutation.ClearReservationID()
	return cuo
}

// SetParkNo sets the "park_no" field.
func (cuo *ConnectorUpdateOne) SetParkNo(s string) *ConnectorUpdateOne {
	cuo.mutation.SetParkNo(s)
	return cuo
}

// SetNillableParkNo sets the "park_no" field if the given value is not nil.
func (cuo *ConnectorUpdateOne) SetNillableParkNo(s *string) *ConnectorUpdateOne {
	if s != nil {
		cuo.SetParkNo(*s)
	}
	return cuo
}

// SetEvseID sets the "evse" edge to the Evse entity by ID.
func (cuo *ConnectorUpdateOne) SetEvseID(id datasource.UUID) *ConnectorUpdateOne {
	cuo.mutation.SetEvseID(id)
	return cuo
}

// SetEvse sets the "evse" edge to the Evse entity.
func (cuo *ConnectorUpdateOne) SetEvse(e *Evse) *ConnectorUpdateOne {
	return cuo.SetEvseID(e.ID)
}

// SetEquipmentID sets the "equipment" edge to the Equipment entity by ID.
func (cuo *ConnectorUpdateOne) SetEquipmentID(id datasource.UUID) *ConnectorUpdateOne {
	cuo.mutation.SetEquipmentID(id)
	return cuo
}

// SetEquipment sets the "equipment" edge to the Equipment entity.
func (cuo *ConnectorUpdateOne) SetEquipment(e *Equipment) *ConnectorUpdateOne {
	return cuo.SetEquipmentID(e.ID)
}

// AddOrderInfoIDs adds the "order_info" edge to the OrderInfo entity by IDs.
func (cuo *ConnectorUpdateOne) AddOrderInfoIDs(ids ...datasource.UUID) *ConnectorUpdateOne {
	cuo.mutation.AddOrderInfoIDs(ids...)
	return cuo
}

// AddOrderInfo adds the "order_info" edges to the OrderInfo entity.
func (cuo *ConnectorUpdateOne) AddOrderInfo(o ...*OrderInfo) *ConnectorUpdateOne {
	ids := make([]datasource.UUID, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return cuo.AddOrderInfoIDs(ids...)
}

// AddReservationIDs adds the "reservation" edge to the Reservation entity by IDs.
func (cuo *ConnectorUpdateOne) AddReservationIDs(ids ...datasource.UUID) *ConnectorUpdateOne {
	cuo.mutation.AddReservationIDs(ids...)
	return cuo
}

// AddReservation adds the "reservation" edges to the Reservation entity.
func (cuo *ConnectorUpdateOne) AddReservation(r ...*Reservation) *ConnectorUpdateOne {
	ids := make([]datasource.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return cuo.AddReservationIDs(ids...)
}

// AddSmartChargingEffectIDs adds the "smart_charging_effect" edge to the SmartChargingEffect entity by IDs.
func (cuo *ConnectorUpdateOne) AddSmartChargingEffectIDs(ids ...datasource.UUID) *ConnectorUpdateOne {
	cuo.mutation.AddSmartChargingEffectIDs(ids...)
	return cuo
}

// AddSmartChargingEffect adds the "smart_charging_effect" edges to the SmartChargingEffect entity.
func (cuo *ConnectorUpdateOne) AddSmartChargingEffect(s ...*SmartChargingEffect) *ConnectorUpdateOne {
	ids := make([]datasource.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return cuo.AddSmartChargingEffectIDs(ids...)
}

// Mutation returns the ConnectorMutation object of the builder.
func (cuo *ConnectorUpdateOne) Mutation() *ConnectorMutation {
	return cuo.mutation
}

// ClearEvse clears the "evse" edge to the Evse entity.
func (cuo *ConnectorUpdateOne) ClearEvse() *ConnectorUpdateOne {
	cuo.mutation.ClearEvse()
	return cuo
}

// ClearEquipment clears the "equipment" edge to the Equipment entity.
func (cuo *ConnectorUpdateOne) ClearEquipment() *ConnectorUpdateOne {
	cuo.mutation.ClearEquipment()
	return cuo
}

// ClearOrderInfo clears all "order_info" edges to the OrderInfo entity.
func (cuo *ConnectorUpdateOne) ClearOrderInfo() *ConnectorUpdateOne {
	cuo.mutation.ClearOrderInfo()
	return cuo
}

// RemoveOrderInfoIDs removes the "order_info" edge to OrderInfo entities by IDs.
func (cuo *ConnectorUpdateOne) RemoveOrderInfoIDs(ids ...datasource.UUID) *ConnectorUpdateOne {
	cuo.mutation.RemoveOrderInfoIDs(ids...)
	return cuo
}

// RemoveOrderInfo removes "order_info" edges to OrderInfo entities.
func (cuo *ConnectorUpdateOne) RemoveOrderInfo(o ...*OrderInfo) *ConnectorUpdateOne {
	ids := make([]datasource.UUID, len(o))
	for i := range o {
		ids[i] = o[i].ID
	}
	return cuo.RemoveOrderInfoIDs(ids...)
}

// ClearReservation clears all "reservation" edges to the Reservation entity.
func (cuo *ConnectorUpdateOne) ClearReservation() *ConnectorUpdateOne {
	cuo.mutation.ClearReservation()
	return cuo
}

// RemoveReservationIDs removes the "reservation" edge to Reservation entities by IDs.
func (cuo *ConnectorUpdateOne) RemoveReservationIDs(ids ...datasource.UUID) *ConnectorUpdateOne {
	cuo.mutation.RemoveReservationIDs(ids...)
	return cuo
}

// RemoveReservation removes "reservation" edges to Reservation entities.
func (cuo *ConnectorUpdateOne) RemoveReservation(r ...*Reservation) *ConnectorUpdateOne {
	ids := make([]datasource.UUID, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return cuo.RemoveReservationIDs(ids...)
}

// ClearSmartChargingEffect clears all "smart_charging_effect" edges to the SmartChargingEffect entity.
func (cuo *ConnectorUpdateOne) ClearSmartChargingEffect() *ConnectorUpdateOne {
	cuo.mutation.ClearSmartChargingEffect()
	return cuo
}

// RemoveSmartChargingEffectIDs removes the "smart_charging_effect" edge to SmartChargingEffect entities by IDs.
func (cuo *ConnectorUpdateOne) RemoveSmartChargingEffectIDs(ids ...datasource.UUID) *ConnectorUpdateOne {
	cuo.mutation.RemoveSmartChargingEffectIDs(ids...)
	return cuo
}

// RemoveSmartChargingEffect removes "smart_charging_effect" edges to SmartChargingEffect entities.
func (cuo *ConnectorUpdateOne) RemoveSmartChargingEffect(s ...*SmartChargingEffect) *ConnectorUpdateOne {
	ids := make([]datasource.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return cuo.RemoveSmartChargingEffectIDs(ids...)
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *ConnectorUpdateOne) Select(field string, fields ...string) *ConnectorUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Connector entity.
func (cuo *ConnectorUpdateOne) Save(ctx context.Context) (*Connector, error) {
	var (
		err  error
		node *Connector
	)
	if len(cuo.hooks) == 0 {
		if err = cuo.check(); err != nil {
			return nil, err
		}
		node, err = cuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ConnectorMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cuo.check(); err != nil {
				return nil, err
			}
			cuo.mutation = mutation
			node, err = cuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cuo.hooks) - 1; i >= 0; i-- {
			if cuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, cuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Connector)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from ConnectorMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *ConnectorUpdateOne) SaveX(ctx context.Context) *Connector {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *ConnectorUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *ConnectorUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *ConnectorUpdateOne) check() error {
	if _, ok := cuo.mutation.EvseID(); cuo.mutation.EvseCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Connector.evse"`)
	}
	if _, ok := cuo.mutation.EquipmentID(); cuo.mutation.EquipmentCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Connector.equipment"`)
	}
	return nil
}

func (cuo *ConnectorUpdateOne) sqlSave(ctx context.Context) (_node *Connector, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   connector.Table,
			Columns: connector.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUint64,
				Column: connector.FieldID,
			},
		},
	}
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Connector.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, connector.FieldID)
		for _, f := range fields {
			if !connector.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != connector.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Version(); ok {
		_spec.SetField(connector.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := cuo.mutation.AddedVersion(); ok {
		_spec.AddField(connector.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := cuo.mutation.UpdatedBy(); ok {
		_spec.SetField(connector.FieldUpdatedBy, field.TypeUint64, value)
	}
	if value, ok := cuo.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(connector.FieldUpdatedBy, field.TypeUint64, value)
	}
	if value, ok := cuo.mutation.UpdatedAt(); ok {
		_spec.SetField(connector.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := cuo.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(connector.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := cuo.mutation.EquipmentSn(); ok {
		_spec.SetField(connector.FieldEquipmentSn, field.TypeString, value)
	}
	if value, ok := cuo.mutation.EvseSerial(); ok {
		_spec.SetField(connector.FieldEvseSerial, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Serial(); ok {
		_spec.SetField(connector.FieldSerial, field.TypeString, value)
	}
	if value, ok := cuo.mutation.CurrentState(); ok {
		_spec.SetField(connector.FieldCurrentState, field.TypeInt, value)
	}
	if value, ok := cuo.mutation.AddedCurrentState(); ok {
		_spec.AddField(connector.FieldCurrentState, field.TypeInt, value)
	}
	if value, ok := cuo.mutation.BeforeState(); ok {
		_spec.SetField(connector.FieldBeforeState, field.TypeInt, value)
	}
	if value, ok := cuo.mutation.AddedBeforeState(); ok {
		_spec.AddField(connector.FieldBeforeState, field.TypeInt, value)
	}
	if value, ok := cuo.mutation.ChargingState(); ok {
		_spec.SetField(connector.FieldChargingState, field.TypeInt, value)
	}
	if value, ok := cuo.mutation.AddedChargingState(); ok {
		_spec.AddField(connector.FieldChargingState, field.TypeInt, value)
	}
	if cuo.mutation.ChargingStateCleared() {
		_spec.ClearField(connector.FieldChargingState, field.TypeInt)
	}
	if value, ok := cuo.mutation.ReservationID(); ok {
		_spec.SetField(connector.FieldReservationID, field.TypeUint64, value)
	}
	if value, ok := cuo.mutation.AddedReservationID(); ok {
		_spec.AddField(connector.FieldReservationID, field.TypeUint64, value)
	}
	if cuo.mutation.ReservationIDCleared() {
		_spec.ClearField(connector.FieldReservationID, field.TypeUint64)
	}
	if value, ok := cuo.mutation.ParkNo(); ok {
		_spec.SetField(connector.FieldParkNo, field.TypeString, value)
	}
	if cuo.mutation.EvseCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   connector.EvseTable,
			Columns: []string{connector.EvseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: evse.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.EvseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   connector.EvseTable,
			Columns: []string{connector.EvseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: evse.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.EquipmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   connector.EquipmentTable,
			Columns: []string{connector.EquipmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: equipment.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.EquipmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   connector.EquipmentTable,
			Columns: []string{connector.EquipmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: equipment.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.OrderInfoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   connector.OrderInfoTable,
			Columns: []string{connector.OrderInfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: orderinfo.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedOrderInfoIDs(); len(nodes) > 0 && !cuo.mutation.OrderInfoCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   connector.OrderInfoTable,
			Columns: []string{connector.OrderInfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: orderinfo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.OrderInfoIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   connector.OrderInfoTable,
			Columns: []string{connector.OrderInfoColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: orderinfo.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.ReservationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   connector.ReservationTable,
			Columns: []string{connector.ReservationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: reservation.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedReservationIDs(); len(nodes) > 0 && !cuo.mutation.ReservationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   connector.ReservationTable,
			Columns: []string{connector.ReservationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: reservation.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.ReservationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   connector.ReservationTable,
			Columns: []string{connector.ReservationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: reservation.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.SmartChargingEffectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   connector.SmartChargingEffectTable,
			Columns: []string{connector.SmartChargingEffectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: smartchargingeffect.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedSmartChargingEffectIDs(); len(nodes) > 0 && !cuo.mutation.SmartChargingEffectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   connector.SmartChargingEffectTable,
			Columns: []string{connector.SmartChargingEffectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: smartchargingeffect.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.SmartChargingEffectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   connector.SmartChargingEffectTable,
			Columns: []string{connector.SmartChargingEffectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUint64,
					Column: smartchargingeffect.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Connector{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{connector.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
